import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "./Shared/Nav";

export const metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};

const poppins = Poppins({weight:['100','200','300','400','500','600','700','800'], subsets: ["latin"] });


export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={poppins.className}
      >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
